version: '3.9'

services:
  bot:
    build: .
    environment:
      - TOKEN=CHANGE_ME
      - CLIENT_ID=CHANGE_ME
      - DATABASE_SERVER=CHANGE_ME
      - DATABASE_USERNAME=CHANGE_ME
      - DATABASE_PASSWORD=CHANGE_ME
      - DATABASE_NAME=CHANGE_ME
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=CHANGE_ME
      - POSTGRES_USER=CHANGE_ME
      - POSTGRES_PASSWORD=CHANGE_ME
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
